
#ODMD GENERATED WORKFLOW, don't change unless you are sure

name: OdmdBuildDefaultVpcRds-Custom,,CdkGithubWF
on:
  workflow_dispatch:
    inputs:
      target_rev_ref:
        description: 'Tag or revision/SHA to checkout'
      aws_credentials:
        type: string
        description: | 
          Your AWS credentials in the format:
          [0123456789_MyRole_profile]
          aws_access_key_id=01234_id
          aws_secret_access_key=56689_secret
          aws_session_token=token0123456789
jobs:
  odmd_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - uses: ondemandenv/build@main
        with:
          aws_credentials: ${{github.event.inputs.aws_credentials}}
        env:
          ODMD_AWS_CREDENTIALS: ${{ secrets['ODMD_AWS_CREDENTIALS'] }}

#